#!/bin/sh
case "$1" in
    configure|reconfigure)
    # Create a default default file if none exists.
	if ! [ -f "/etc/default/msktutil" ]; then
	    cat > /etc/default/msktutil <<EOF
# Whether to call msktutil --auto-update to rotate the password every 30 days or not.
# Set to "false" or "true"
AUTOUPDATE_ENABLED="false"

# Any other args to pass to msktutil (e.g. -h hostname, --verbose, etc)
AUTOUPDATE_OPTIONS=""
EOF
	fi
	;;
    abort-upgrade|abort-remove|abort-deconfigure)
        # We don't have to do anything because we didn't do anything in prerm
	exit 0
	;;
    *)
	echo "postinst called with unknown argument \`$1'" >&2
	exit 1
	;;
esac
